"""remove fact_date from Passenger model

Revision ID: 3e23beee3d58
Revises: 35d3763ca7e5
Create Date: 2026-03-29 22:18:57.921473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e23beee3d58'
down_revision: Union[str, Sequence[str], None] = '35d3763ca7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passengers', 'fact_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passengers', sa.Column('fact_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
