"""add planning date in Passenger

Revision ID: 5fb4004a3a36
Revises: 3e23beee3d58
Create Date: 2026-03-29 22:20:09.352377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb4004a3a36'
down_revision: Union[str, Sequence[str], None] = '3e23beee3d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passengers', sa.Column('planning_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passengers', 'planning_date')
    # ### end Alembic commands ###
