"""add flight_route_id to Passenger

Revision ID: aa6d0de1d962
Revises: 5fb4004a3a36
Create Date: 2026-03-29 23:11:34.178472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6d0de1d962'
down_revision: Union[str, Sequence[str], None] = '5fb4004a3a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passengers', sa.Column('flight_route_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'passengers', 'flight_routes', ['flight_route_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passengers', type_='foreignkey')
    op.drop_column('passengers', 'flight_route_id')
    # ### end Alembic commands ###
