"""add main_dispatcher_date to Passenger

Revision ID: b8d0ce7a59b0
Revises: aa6d0de1d962
Create Date: 2026-05-09 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d0ce7a59b0'
down_revision: Union[str, Sequence[str], None] = 'aa6d0de1d962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passengers', sa.Column('main_dispatcher_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passengers', 'main_dispatcher_date')
    # ### end Alembic commands ###
